### ISSUE TITLE
Dataset files are missing

### ISSUE THREAD

**Issue by alesaccoia** [soleti/oc_camera#1]
Hi! I'm a  political science student: I'd like to understand how these algorithm works, for learning.. I would like to know how to get the needed datasets and maybe the source you got them from. thank you!

**Comment by soleti** [comment]
Hi, the dataset was provided by OpenPolis (https://parlamento18.openpolis.it) through a private request. You can try to send them an email, they are usually willing to give the data as long as you cite the source.

**Comment by alesaccoia** [comment]
ok! don't worry then.. grazie!
